name: Release

on:
  release:
    types: [ published ]
  workflow_dispatch:

env:
  SOLUTION_NAME: AutoSweep
  ZIP_PATH: bin\Release\out\autoSweep

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.3

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"

      - name: Setup Secrets
        run: |
          echo '${{ secrets.SECRETS_CS }}' > Paissa/Secrets.cs

      - name: Build
        run: |
          dotnet restore
          dotnet build -c Release

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: ReleaseZip
          path: ${{ env.ZIP_PATH }}
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ReleaseZip
          path: out

      - name: Prepare for release
        run: |
          mv out/latest.zip out/autoSweep.zip

      - name: Update release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            out/autoSweep.zip
            out/autoSweep.json

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: ReleaseArtifact
          path: out

      - name: Trigger plugin repo update
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: zhudotexe/FFXIV_DalamudPlugins
          event-type: new-release
          
  release-dalamudofficial:
    # on release publish only
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ReleaseZip
          path: out
          
      - name: Checkout DalamudPlugins
        uses: actions/checkout@v3
        with:
          repository: 'goatcorp/DalamudPlugins'
          path: DalamudPlugins
          
      - name: Copy dist files
        run: |
          cp out/latest.zip DalamudPlugins/autoSweep/latest.zip
          cp out/autoSweep.json DalamudPlugins/autoSweep/autoSweep.json
          cp -r out/images DalamudPlugins/autoSweep/images
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: DalamudPlugins
          commit-message: update PaissaHouse to ${{ github.event.release.tag_name }}
          delete-branch: true
          push-to-fork: zhudotexe/DalamudPlugins
          title: Update PaissaHouse to ${{ github.event.release.name }}
          body: |
            ${{ github.event.release.body }}
            
            *This PR was automatically generated by the PaissaHouse build system ([link to run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})).*
